
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model SystemConfig
 * 
 */
export type SystemConfig = Prisma.SystemConfigModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Task
 * 
 */
export type Task = Prisma.TaskModel
/**
 * Model WebhookConfig
 * 
 */
export type WebhookConfig = Prisma.WebhookConfigModel
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Purpose
 * 
 */
export type Purpose = Prisma.PurposeModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Image
 * 
 */
export type Image = Prisma.ImageModel
/**
 * Model Activity
 * 
 */
export type Activity = Prisma.ActivityModel
/**
 * Model Inventory
 * 
 */
export type Inventory = Prisma.InventoryModel
/**
 * Model InventoryLog
 * 
 */
export type InventoryLog = Prisma.InventoryLogModel
/**
 * Model VariantOption
 * 
 */
export type VariantOption = Prisma.VariantOptionModel
/**
 * Model VariantValue
 * 
 */
export type VariantValue = Prisma.VariantValueModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model VariantInventoryLog
 * 
 */
export type VariantInventoryLog = Prisma.VariantInventoryLogModel
/**
 * Model VariantImage
 * 
 */
export type VariantImage = Prisma.VariantImageModel
/**
 * Model ContactMessage
 * 
 */
export type ContactMessage = Prisma.ContactMessageModel
