
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Purpose` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Purpose
 * 
 */
export type PurposeModel = runtime.Types.Result.DefaultSelection<Prisma.$PurposePayload>

export type AggregatePurpose = {
  _count: PurposeCountAggregateOutputType | null
  _min: PurposeMinAggregateOutputType | null
  _max: PurposeMaxAggregateOutputType | null
}

export type PurposeMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PurposeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PurposeCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PurposeMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type PurposeMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type PurposeCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PurposeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Purpose to aggregate.
   */
  where?: Prisma.PurposeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Purposes to fetch.
   */
  orderBy?: Prisma.PurposeOrderByWithRelationInput | Prisma.PurposeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PurposeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Purposes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Purposes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Purposes
  **/
  _count?: true | PurposeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PurposeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PurposeMaxAggregateInputType
}

export type GetPurposeAggregateType<T extends PurposeAggregateArgs> = {
      [P in keyof T & keyof AggregatePurpose]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePurpose[P]>
    : Prisma.GetScalarType<T[P], AggregatePurpose[P]>
}




export type PurposeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PurposeWhereInput
  orderBy?: Prisma.PurposeOrderByWithAggregationInput | Prisma.PurposeOrderByWithAggregationInput[]
  by: Prisma.PurposeScalarFieldEnum[] | Prisma.PurposeScalarFieldEnum
  having?: Prisma.PurposeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PurposeCountAggregateInputType | true
  _min?: PurposeMinAggregateInputType
  _max?: PurposeMaxAggregateInputType
}

export type PurposeGroupByOutputType = {
  id: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: PurposeCountAggregateOutputType | null
  _min: PurposeMinAggregateOutputType | null
  _max: PurposeMaxAggregateOutputType | null
}

type GetPurposeGroupByPayload<T extends PurposeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PurposeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PurposeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PurposeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PurposeGroupByOutputType[P]>
      }
    >
  >



export type PurposeWhereInput = {
  AND?: Prisma.PurposeWhereInput | Prisma.PurposeWhereInput[]
  OR?: Prisma.PurposeWhereInput[]
  NOT?: Prisma.PurposeWhereInput | Prisma.PurposeWhereInput[]
  id?: Prisma.StringFilter<"Purpose"> | string
  name?: Prisma.StringFilter<"Purpose"> | string
  createdAt?: Prisma.DateTimeFilter<"Purpose"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Purpose"> | Date | string
  products?: Prisma.ProductListRelationFilter
  categories?: Prisma.CategoryListRelationFilter
}

export type PurposeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
  categories?: Prisma.CategoryOrderByRelationAggregateInput
}

export type PurposeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.PurposeWhereInput | Prisma.PurposeWhereInput[]
  OR?: Prisma.PurposeWhereInput[]
  NOT?: Prisma.PurposeWhereInput | Prisma.PurposeWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Purpose"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Purpose"> | Date | string
  products?: Prisma.ProductListRelationFilter
  categories?: Prisma.CategoryListRelationFilter
}, "id" | "name">

export type PurposeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PurposeCountOrderByAggregateInput
  _max?: Prisma.PurposeMaxOrderByAggregateInput
  _min?: Prisma.PurposeMinOrderByAggregateInput
}

export type PurposeScalarWhereWithAggregatesInput = {
  AND?: Prisma.PurposeScalarWhereWithAggregatesInput | Prisma.PurposeScalarWhereWithAggregatesInput[]
  OR?: Prisma.PurposeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PurposeScalarWhereWithAggregatesInput | Prisma.PurposeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Purpose"> | string
  name?: Prisma.StringWithAggregatesFilter<"Purpose"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Purpose"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Purpose"> | Date | string
}

export type PurposeCreateInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutPurposeInput
  categories?: Prisma.CategoryCreateNestedManyWithoutPurposesInput
}

export type PurposeUncheckedCreateInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutPurposeInput
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutPurposesInput
}

export type PurposeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutPurposeNestedInput
  categories?: Prisma.CategoryUpdateManyWithoutPurposesNestedInput
}

export type PurposeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutPurposeNestedInput
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutPurposesNestedInput
}

export type PurposeCreateManyInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PurposeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PurposeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PurposeListRelationFilter = {
  every?: Prisma.PurposeWhereInput
  some?: Prisma.PurposeWhereInput
  none?: Prisma.PurposeWhereInput
}

export type PurposeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PurposeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PurposeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PurposeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PurposeNullableScalarRelationFilter = {
  is?: Prisma.PurposeWhereInput | null
  isNot?: Prisma.PurposeWhereInput | null
}

export type PurposeCreateNestedManyWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.PurposeCreateWithoutCategoriesInput, Prisma.PurposeUncheckedCreateWithoutCategoriesInput> | Prisma.PurposeCreateWithoutCategoriesInput[] | Prisma.PurposeUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.PurposeCreateOrConnectWithoutCategoriesInput | Prisma.PurposeCreateOrConnectWithoutCategoriesInput[]
  connect?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
}

export type PurposeUncheckedCreateNestedManyWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.PurposeCreateWithoutCategoriesInput, Prisma.PurposeUncheckedCreateWithoutCategoriesInput> | Prisma.PurposeCreateWithoutCategoriesInput[] | Prisma.PurposeUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.PurposeCreateOrConnectWithoutCategoriesInput | Prisma.PurposeCreateOrConnectWithoutCategoriesInput[]
  connect?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
}

export type PurposeUpdateManyWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.PurposeCreateWithoutCategoriesInput, Prisma.PurposeUncheckedCreateWithoutCategoriesInput> | Prisma.PurposeCreateWithoutCategoriesInput[] | Prisma.PurposeUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.PurposeCreateOrConnectWithoutCategoriesInput | Prisma.PurposeCreateOrConnectWithoutCategoriesInput[]
  upsert?: Prisma.PurposeUpsertWithWhereUniqueWithoutCategoriesInput | Prisma.PurposeUpsertWithWhereUniqueWithoutCategoriesInput[]
  set?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  disconnect?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  delete?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  connect?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  update?: Prisma.PurposeUpdateWithWhereUniqueWithoutCategoriesInput | Prisma.PurposeUpdateWithWhereUniqueWithoutCategoriesInput[]
  updateMany?: Prisma.PurposeUpdateManyWithWhereWithoutCategoriesInput | Prisma.PurposeUpdateManyWithWhereWithoutCategoriesInput[]
  deleteMany?: Prisma.PurposeScalarWhereInput | Prisma.PurposeScalarWhereInput[]
}

export type PurposeUncheckedUpdateManyWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.PurposeCreateWithoutCategoriesInput, Prisma.PurposeUncheckedCreateWithoutCategoriesInput> | Prisma.PurposeCreateWithoutCategoriesInput[] | Prisma.PurposeUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.PurposeCreateOrConnectWithoutCategoriesInput | Prisma.PurposeCreateOrConnectWithoutCategoriesInput[]
  upsert?: Prisma.PurposeUpsertWithWhereUniqueWithoutCategoriesInput | Prisma.PurposeUpsertWithWhereUniqueWithoutCategoriesInput[]
  set?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  disconnect?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  delete?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  connect?: Prisma.PurposeWhereUniqueInput | Prisma.PurposeWhereUniqueInput[]
  update?: Prisma.PurposeUpdateWithWhereUniqueWithoutCategoriesInput | Prisma.PurposeUpdateWithWhereUniqueWithoutCategoriesInput[]
  updateMany?: Prisma.PurposeUpdateManyWithWhereWithoutCategoriesInput | Prisma.PurposeUpdateManyWithWhereWithoutCategoriesInput[]
  deleteMany?: Prisma.PurposeScalarWhereInput | Prisma.PurposeScalarWhereInput[]
}

export type PurposeCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.PurposeCreateWithoutProductsInput, Prisma.PurposeUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.PurposeCreateOrConnectWithoutProductsInput
  connect?: Prisma.PurposeWhereUniqueInput
}

export type PurposeUpdateOneWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.PurposeCreateWithoutProductsInput, Prisma.PurposeUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.PurposeCreateOrConnectWithoutProductsInput
  upsert?: Prisma.PurposeUpsertWithoutProductsInput
  disconnect?: Prisma.PurposeWhereInput | boolean
  delete?: Prisma.PurposeWhereInput | boolean
  connect?: Prisma.PurposeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PurposeUpdateToOneWithWhereWithoutProductsInput, Prisma.PurposeUpdateWithoutProductsInput>, Prisma.PurposeUncheckedUpdateWithoutProductsInput>
}

export type PurposeCreateWithoutCategoriesInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutPurposeInput
}

export type PurposeUncheckedCreateWithoutCategoriesInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutPurposeInput
}

export type PurposeCreateOrConnectWithoutCategoriesInput = {
  where: Prisma.PurposeWhereUniqueInput
  create: Prisma.XOR<Prisma.PurposeCreateWithoutCategoriesInput, Prisma.PurposeUncheckedCreateWithoutCategoriesInput>
}

export type PurposeUpsertWithWhereUniqueWithoutCategoriesInput = {
  where: Prisma.PurposeWhereUniqueInput
  update: Prisma.XOR<Prisma.PurposeUpdateWithoutCategoriesInput, Prisma.PurposeUncheckedUpdateWithoutCategoriesInput>
  create: Prisma.XOR<Prisma.PurposeCreateWithoutCategoriesInput, Prisma.PurposeUncheckedCreateWithoutCategoriesInput>
}

export type PurposeUpdateWithWhereUniqueWithoutCategoriesInput = {
  where: Prisma.PurposeWhereUniqueInput
  data: Prisma.XOR<Prisma.PurposeUpdateWithoutCategoriesInput, Prisma.PurposeUncheckedUpdateWithoutCategoriesInput>
}

export type PurposeUpdateManyWithWhereWithoutCategoriesInput = {
  where: Prisma.PurposeScalarWhereInput
  data: Prisma.XOR<Prisma.PurposeUpdateManyMutationInput, Prisma.PurposeUncheckedUpdateManyWithoutCategoriesInput>
}

export type PurposeScalarWhereInput = {
  AND?: Prisma.PurposeScalarWhereInput | Prisma.PurposeScalarWhereInput[]
  OR?: Prisma.PurposeScalarWhereInput[]
  NOT?: Prisma.PurposeScalarWhereInput | Prisma.PurposeScalarWhereInput[]
  id?: Prisma.StringFilter<"Purpose"> | string
  name?: Prisma.StringFilter<"Purpose"> | string
  createdAt?: Prisma.DateTimeFilter<"Purpose"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Purpose"> | Date | string
}

export type PurposeCreateWithoutProductsInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  categories?: Prisma.CategoryCreateNestedManyWithoutPurposesInput
}

export type PurposeUncheckedCreateWithoutProductsInput = {
  id: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutPurposesInput
}

export type PurposeCreateOrConnectWithoutProductsInput = {
  where: Prisma.PurposeWhereUniqueInput
  create: Prisma.XOR<Prisma.PurposeCreateWithoutProductsInput, Prisma.PurposeUncheckedCreateWithoutProductsInput>
}

export type PurposeUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.PurposeUpdateWithoutProductsInput, Prisma.PurposeUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.PurposeCreateWithoutProductsInput, Prisma.PurposeUncheckedCreateWithoutProductsInput>
  where?: Prisma.PurposeWhereInput
}

export type PurposeUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.PurposeWhereInput
  data: Prisma.XOR<Prisma.PurposeUpdateWithoutProductsInput, Prisma.PurposeUncheckedUpdateWithoutProductsInput>
}

export type PurposeUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  categories?: Prisma.CategoryUpdateManyWithoutPurposesNestedInput
}

export type PurposeUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutPurposesNestedInput
}

export type PurposeUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutPurposeNestedInput
}

export type PurposeUncheckedUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutPurposeNestedInput
}

export type PurposeUncheckedUpdateManyWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PurposeCountOutputType
 */

export type PurposeCountOutputType = {
  products: number
  categories: number
}

export type PurposeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | PurposeCountOutputTypeCountProductsArgs
  categories?: boolean | PurposeCountOutputTypeCountCategoriesArgs
}

/**
 * PurposeCountOutputType without action
 */
export type PurposeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurposeCountOutputType
   */
  select?: Prisma.PurposeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PurposeCountOutputType without action
 */
export type PurposeCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}

/**
 * PurposeCountOutputType without action
 */
export type PurposeCountOutputTypeCountCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CategoryWhereInput
}


export type PurposeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  products?: boolean | Prisma.Purpose$productsArgs<ExtArgs>
  categories?: boolean | Prisma.Purpose$categoriesArgs<ExtArgs>
  _count?: boolean | Prisma.PurposeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["purpose"]>

export type PurposeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["purpose"]>

export type PurposeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["purpose"]>

export type PurposeSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PurposeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["purpose"]>
export type PurposeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.Purpose$productsArgs<ExtArgs>
  categories?: boolean | Prisma.Purpose$categoriesArgs<ExtArgs>
  _count?: boolean | Prisma.PurposeCountOutputTypeDefaultArgs<ExtArgs>
}
export type PurposeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PurposeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PurposePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Purpose"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
    categories: Prisma.$CategoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["purpose"]>
  composites: {}
}

export type PurposeGetPayload<S extends boolean | null | undefined | PurposeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PurposePayload, S>

export type PurposeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PurposeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PurposeCountAggregateInputType | true
  }

export interface PurposeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Purpose'], meta: { name: 'Purpose' } }
  /**
   * Find zero or one Purpose that matches the filter.
   * @param {PurposeFindUniqueArgs} args - Arguments to find a Purpose
   * @example
   * // Get one Purpose
   * const purpose = await prisma.purpose.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PurposeFindUniqueArgs>(args: Prisma.SelectSubset<T, PurposeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Purpose that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PurposeFindUniqueOrThrowArgs} args - Arguments to find a Purpose
   * @example
   * // Get one Purpose
   * const purpose = await prisma.purpose.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PurposeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PurposeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Purpose that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeFindFirstArgs} args - Arguments to find a Purpose
   * @example
   * // Get one Purpose
   * const purpose = await prisma.purpose.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PurposeFindFirstArgs>(args?: Prisma.SelectSubset<T, PurposeFindFirstArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Purpose that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeFindFirstOrThrowArgs} args - Arguments to find a Purpose
   * @example
   * // Get one Purpose
   * const purpose = await prisma.purpose.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PurposeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PurposeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Purposes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Purposes
   * const purposes = await prisma.purpose.findMany()
   * 
   * // Get first 10 Purposes
   * const purposes = await prisma.purpose.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const purposeWithIdOnly = await prisma.purpose.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PurposeFindManyArgs>(args?: Prisma.SelectSubset<T, PurposeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Purpose.
   * @param {PurposeCreateArgs} args - Arguments to create a Purpose.
   * @example
   * // Create one Purpose
   * const Purpose = await prisma.purpose.create({
   *   data: {
   *     // ... data to create a Purpose
   *   }
   * })
   * 
   */
  create<T extends PurposeCreateArgs>(args: Prisma.SelectSubset<T, PurposeCreateArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Purposes.
   * @param {PurposeCreateManyArgs} args - Arguments to create many Purposes.
   * @example
   * // Create many Purposes
   * const purpose = await prisma.purpose.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PurposeCreateManyArgs>(args?: Prisma.SelectSubset<T, PurposeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Purposes and returns the data saved in the database.
   * @param {PurposeCreateManyAndReturnArgs} args - Arguments to create many Purposes.
   * @example
   * // Create many Purposes
   * const purpose = await prisma.purpose.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Purposes and only return the `id`
   * const purposeWithIdOnly = await prisma.purpose.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PurposeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PurposeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Purpose.
   * @param {PurposeDeleteArgs} args - Arguments to delete one Purpose.
   * @example
   * // Delete one Purpose
   * const Purpose = await prisma.purpose.delete({
   *   where: {
   *     // ... filter to delete one Purpose
   *   }
   * })
   * 
   */
  delete<T extends PurposeDeleteArgs>(args: Prisma.SelectSubset<T, PurposeDeleteArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Purpose.
   * @param {PurposeUpdateArgs} args - Arguments to update one Purpose.
   * @example
   * // Update one Purpose
   * const purpose = await prisma.purpose.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PurposeUpdateArgs>(args: Prisma.SelectSubset<T, PurposeUpdateArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Purposes.
   * @param {PurposeDeleteManyArgs} args - Arguments to filter Purposes to delete.
   * @example
   * // Delete a few Purposes
   * const { count } = await prisma.purpose.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PurposeDeleteManyArgs>(args?: Prisma.SelectSubset<T, PurposeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Purposes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Purposes
   * const purpose = await prisma.purpose.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PurposeUpdateManyArgs>(args: Prisma.SelectSubset<T, PurposeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Purposes and returns the data updated in the database.
   * @param {PurposeUpdateManyAndReturnArgs} args - Arguments to update many Purposes.
   * @example
   * // Update many Purposes
   * const purpose = await prisma.purpose.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Purposes and only return the `id`
   * const purposeWithIdOnly = await prisma.purpose.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PurposeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PurposeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Purpose.
   * @param {PurposeUpsertArgs} args - Arguments to update or create a Purpose.
   * @example
   * // Update or create a Purpose
   * const purpose = await prisma.purpose.upsert({
   *   create: {
   *     // ... data to create a Purpose
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Purpose we want to update
   *   }
   * })
   */
  upsert<T extends PurposeUpsertArgs>(args: Prisma.SelectSubset<T, PurposeUpsertArgs<ExtArgs>>): Prisma.Prisma__PurposeClient<runtime.Types.Result.GetResult<Prisma.$PurposePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Purposes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeCountArgs} args - Arguments to filter Purposes to count.
   * @example
   * // Count the number of Purposes
   * const count = await prisma.purpose.count({
   *   where: {
   *     // ... the filter for the Purposes we want to count
   *   }
   * })
  **/
  count<T extends PurposeCountArgs>(
    args?: Prisma.Subset<T, PurposeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PurposeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Purpose.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PurposeAggregateArgs>(args: Prisma.Subset<T, PurposeAggregateArgs>): Prisma.PrismaPromise<GetPurposeAggregateType<T>>

  /**
   * Group by Purpose.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurposeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PurposeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PurposeGroupByArgs['orderBy'] }
      : { orderBy?: PurposeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PurposeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPurposeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Purpose model
 */
readonly fields: PurposeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Purpose.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PurposeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.Purpose$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Purpose$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  categories<T extends Prisma.Purpose$categoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Purpose$categoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Purpose model
 */
export interface PurposeFieldRefs {
  readonly id: Prisma.FieldRef<"Purpose", 'String'>
  readonly name: Prisma.FieldRef<"Purpose", 'String'>
  readonly createdAt: Prisma.FieldRef<"Purpose", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Purpose", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Purpose findUnique
 */
export type PurposeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * Filter, which Purpose to fetch.
   */
  where: Prisma.PurposeWhereUniqueInput
}

/**
 * Purpose findUniqueOrThrow
 */
export type PurposeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * Filter, which Purpose to fetch.
   */
  where: Prisma.PurposeWhereUniqueInput
}

/**
 * Purpose findFirst
 */
export type PurposeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * Filter, which Purpose to fetch.
   */
  where?: Prisma.PurposeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Purposes to fetch.
   */
  orderBy?: Prisma.PurposeOrderByWithRelationInput | Prisma.PurposeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Purposes.
   */
  cursor?: Prisma.PurposeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Purposes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Purposes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Purposes.
   */
  distinct?: Prisma.PurposeScalarFieldEnum | Prisma.PurposeScalarFieldEnum[]
}

/**
 * Purpose findFirstOrThrow
 */
export type PurposeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * Filter, which Purpose to fetch.
   */
  where?: Prisma.PurposeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Purposes to fetch.
   */
  orderBy?: Prisma.PurposeOrderByWithRelationInput | Prisma.PurposeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Purposes.
   */
  cursor?: Prisma.PurposeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Purposes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Purposes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Purposes.
   */
  distinct?: Prisma.PurposeScalarFieldEnum | Prisma.PurposeScalarFieldEnum[]
}

/**
 * Purpose findMany
 */
export type PurposeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * Filter, which Purposes to fetch.
   */
  where?: Prisma.PurposeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Purposes to fetch.
   */
  orderBy?: Prisma.PurposeOrderByWithRelationInput | Prisma.PurposeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Purposes.
   */
  cursor?: Prisma.PurposeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Purposes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Purposes.
   */
  skip?: number
  distinct?: Prisma.PurposeScalarFieldEnum | Prisma.PurposeScalarFieldEnum[]
}

/**
 * Purpose create
 */
export type PurposeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * The data needed to create a Purpose.
   */
  data: Prisma.XOR<Prisma.PurposeCreateInput, Prisma.PurposeUncheckedCreateInput>
}

/**
 * Purpose createMany
 */
export type PurposeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Purposes.
   */
  data: Prisma.PurposeCreateManyInput | Prisma.PurposeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Purpose createManyAndReturn
 */
export type PurposeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * The data used to create many Purposes.
   */
  data: Prisma.PurposeCreateManyInput | Prisma.PurposeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Purpose update
 */
export type PurposeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * The data needed to update a Purpose.
   */
  data: Prisma.XOR<Prisma.PurposeUpdateInput, Prisma.PurposeUncheckedUpdateInput>
  /**
   * Choose, which Purpose to update.
   */
  where: Prisma.PurposeWhereUniqueInput
}

/**
 * Purpose updateMany
 */
export type PurposeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Purposes.
   */
  data: Prisma.XOR<Prisma.PurposeUpdateManyMutationInput, Prisma.PurposeUncheckedUpdateManyInput>
  /**
   * Filter which Purposes to update
   */
  where?: Prisma.PurposeWhereInput
  /**
   * Limit how many Purposes to update.
   */
  limit?: number
}

/**
 * Purpose updateManyAndReturn
 */
export type PurposeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * The data used to update Purposes.
   */
  data: Prisma.XOR<Prisma.PurposeUpdateManyMutationInput, Prisma.PurposeUncheckedUpdateManyInput>
  /**
   * Filter which Purposes to update
   */
  where?: Prisma.PurposeWhereInput
  /**
   * Limit how many Purposes to update.
   */
  limit?: number
}

/**
 * Purpose upsert
 */
export type PurposeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * The filter to search for the Purpose to update in case it exists.
   */
  where: Prisma.PurposeWhereUniqueInput
  /**
   * In case the Purpose found by the `where` argument doesn't exist, create a new Purpose with this data.
   */
  create: Prisma.XOR<Prisma.PurposeCreateInput, Prisma.PurposeUncheckedCreateInput>
  /**
   * In case the Purpose was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PurposeUpdateInput, Prisma.PurposeUncheckedUpdateInput>
}

/**
 * Purpose delete
 */
export type PurposeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
  /**
   * Filter which Purpose to delete.
   */
  where: Prisma.PurposeWhereUniqueInput
}

/**
 * Purpose deleteMany
 */
export type PurposeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Purposes to delete
   */
  where?: Prisma.PurposeWhereInput
  /**
   * Limit how many Purposes to delete.
   */
  limit?: number
}

/**
 * Purpose.products
 */
export type Purpose$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Purpose.categories
 */
export type Purpose$categoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  cursor?: Prisma.CategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Purpose without action
 */
export type PurposeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purpose
   */
  select?: Prisma.PurposeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purpose
   */
  omit?: Prisma.PurposeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurposeInclude<ExtArgs> | null
}
