
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VariantInventoryLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VariantInventoryLog
 * 
 */
export type VariantInventoryLogModel = runtime.Types.Result.DefaultSelection<Prisma.$VariantInventoryLogPayload>

export type AggregateVariantInventoryLog = {
  _count: VariantInventoryLogCountAggregateOutputType | null
  _avg: VariantInventoryLogAvgAggregateOutputType | null
  _sum: VariantInventoryLogSumAggregateOutputType | null
  _min: VariantInventoryLogMinAggregateOutputType | null
  _max: VariantInventoryLogMaxAggregateOutputType | null
}

export type VariantInventoryLogAvgAggregateOutputType = {
  delta: number | null
}

export type VariantInventoryLogSumAggregateOutputType = {
  delta: number | null
}

export type VariantInventoryLogMinAggregateOutputType = {
  id: string | null
  variantId: string | null
  userId: string | null
  delta: number | null
  reason: string | null
  note: string | null
  createdAt: Date | null
}

export type VariantInventoryLogMaxAggregateOutputType = {
  id: string | null
  variantId: string | null
  userId: string | null
  delta: number | null
  reason: string | null
  note: string | null
  createdAt: Date | null
}

export type VariantInventoryLogCountAggregateOutputType = {
  id: number
  variantId: number
  userId: number
  delta: number
  reason: number
  note: number
  createdAt: number
  _all: number
}


export type VariantInventoryLogAvgAggregateInputType = {
  delta?: true
}

export type VariantInventoryLogSumAggregateInputType = {
  delta?: true
}

export type VariantInventoryLogMinAggregateInputType = {
  id?: true
  variantId?: true
  userId?: true
  delta?: true
  reason?: true
  note?: true
  createdAt?: true
}

export type VariantInventoryLogMaxAggregateInputType = {
  id?: true
  variantId?: true
  userId?: true
  delta?: true
  reason?: true
  note?: true
  createdAt?: true
}

export type VariantInventoryLogCountAggregateInputType = {
  id?: true
  variantId?: true
  userId?: true
  delta?: true
  reason?: true
  note?: true
  createdAt?: true
  _all?: true
}

export type VariantInventoryLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VariantInventoryLog to aggregate.
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VariantInventoryLogs to fetch.
   */
  orderBy?: Prisma.VariantInventoryLogOrderByWithRelationInput | Prisma.VariantInventoryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VariantInventoryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VariantInventoryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VariantInventoryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VariantInventoryLogs
  **/
  _count?: true | VariantInventoryLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VariantInventoryLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VariantInventoryLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VariantInventoryLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VariantInventoryLogMaxAggregateInputType
}

export type GetVariantInventoryLogAggregateType<T extends VariantInventoryLogAggregateArgs> = {
      [P in keyof T & keyof AggregateVariantInventoryLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVariantInventoryLog[P]>
    : Prisma.GetScalarType<T[P], AggregateVariantInventoryLog[P]>
}




export type VariantInventoryLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VariantInventoryLogWhereInput
  orderBy?: Prisma.VariantInventoryLogOrderByWithAggregationInput | Prisma.VariantInventoryLogOrderByWithAggregationInput[]
  by: Prisma.VariantInventoryLogScalarFieldEnum[] | Prisma.VariantInventoryLogScalarFieldEnum
  having?: Prisma.VariantInventoryLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VariantInventoryLogCountAggregateInputType | true
  _avg?: VariantInventoryLogAvgAggregateInputType
  _sum?: VariantInventoryLogSumAggregateInputType
  _min?: VariantInventoryLogMinAggregateInputType
  _max?: VariantInventoryLogMaxAggregateInputType
}

export type VariantInventoryLogGroupByOutputType = {
  id: string
  variantId: string
  userId: string
  delta: number
  reason: string
  note: string | null
  createdAt: Date
  _count: VariantInventoryLogCountAggregateOutputType | null
  _avg: VariantInventoryLogAvgAggregateOutputType | null
  _sum: VariantInventoryLogSumAggregateOutputType | null
  _min: VariantInventoryLogMinAggregateOutputType | null
  _max: VariantInventoryLogMaxAggregateOutputType | null
}

type GetVariantInventoryLogGroupByPayload<T extends VariantInventoryLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VariantInventoryLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VariantInventoryLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VariantInventoryLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VariantInventoryLogGroupByOutputType[P]>
      }
    >
  >



export type VariantInventoryLogWhereInput = {
  AND?: Prisma.VariantInventoryLogWhereInput | Prisma.VariantInventoryLogWhereInput[]
  OR?: Prisma.VariantInventoryLogWhereInput[]
  NOT?: Prisma.VariantInventoryLogWhereInput | Prisma.VariantInventoryLogWhereInput[]
  id?: Prisma.StringFilter<"VariantInventoryLog"> | string
  variantId?: Prisma.StringFilter<"VariantInventoryLog"> | string
  userId?: Prisma.StringFilter<"VariantInventoryLog"> | string
  delta?: Prisma.IntFilter<"VariantInventoryLog"> | number
  reason?: Prisma.StringFilter<"VariantInventoryLog"> | string
  note?: Prisma.StringNullableFilter<"VariantInventoryLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VariantInventoryLog"> | Date | string
  variant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type VariantInventoryLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  variant?: Prisma.ProductVariantOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type VariantInventoryLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VariantInventoryLogWhereInput | Prisma.VariantInventoryLogWhereInput[]
  OR?: Prisma.VariantInventoryLogWhereInput[]
  NOT?: Prisma.VariantInventoryLogWhereInput | Prisma.VariantInventoryLogWhereInput[]
  variantId?: Prisma.StringFilter<"VariantInventoryLog"> | string
  userId?: Prisma.StringFilter<"VariantInventoryLog"> | string
  delta?: Prisma.IntFilter<"VariantInventoryLog"> | number
  reason?: Prisma.StringFilter<"VariantInventoryLog"> | string
  note?: Prisma.StringNullableFilter<"VariantInventoryLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VariantInventoryLog"> | Date | string
  variant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type VariantInventoryLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.VariantInventoryLogCountOrderByAggregateInput
  _avg?: Prisma.VariantInventoryLogAvgOrderByAggregateInput
  _max?: Prisma.VariantInventoryLogMaxOrderByAggregateInput
  _min?: Prisma.VariantInventoryLogMinOrderByAggregateInput
  _sum?: Prisma.VariantInventoryLogSumOrderByAggregateInput
}

export type VariantInventoryLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.VariantInventoryLogScalarWhereWithAggregatesInput | Prisma.VariantInventoryLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.VariantInventoryLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VariantInventoryLogScalarWhereWithAggregatesInput | Prisma.VariantInventoryLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VariantInventoryLog"> | string
  variantId?: Prisma.StringWithAggregatesFilter<"VariantInventoryLog"> | string
  userId?: Prisma.StringWithAggregatesFilter<"VariantInventoryLog"> | string
  delta?: Prisma.IntWithAggregatesFilter<"VariantInventoryLog"> | number
  reason?: Prisma.StringWithAggregatesFilter<"VariantInventoryLog"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"VariantInventoryLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VariantInventoryLog"> | Date | string
}

export type VariantInventoryLogCreateInput = {
  id?: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
  variant: Prisma.ProductVariantCreateNestedOneWithoutInventoryLogsInput
  user: Prisma.UserCreateNestedOneWithoutVariantInventoryLogsInput
}

export type VariantInventoryLogUncheckedCreateInput = {
  id?: string
  variantId: string
  userId: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
}

export type VariantInventoryLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.ProductVariantUpdateOneRequiredWithoutInventoryLogsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVariantInventoryLogsNestedInput
}

export type VariantInventoryLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VariantInventoryLogCreateManyInput = {
  id?: string
  variantId: string
  userId: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
}

export type VariantInventoryLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VariantInventoryLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VariantInventoryLogListRelationFilter = {
  every?: Prisma.VariantInventoryLogWhereInput
  some?: Prisma.VariantInventoryLogWhereInput
  none?: Prisma.VariantInventoryLogWhereInput
}

export type VariantInventoryLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VariantInventoryLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VariantInventoryLogAvgOrderByAggregateInput = {
  delta?: Prisma.SortOrder
}

export type VariantInventoryLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VariantInventoryLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VariantInventoryLogSumOrderByAggregateInput = {
  delta?: Prisma.SortOrder
}

export type VariantInventoryLogCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutUserInput, Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput> | Prisma.VariantInventoryLogCreateWithoutUserInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput | Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyUserInputEnvelope
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
}

export type VariantInventoryLogUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutUserInput, Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput> | Prisma.VariantInventoryLogCreateWithoutUserInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput | Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyUserInputEnvelope
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
}

export type VariantInventoryLogUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutUserInput, Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput> | Prisma.VariantInventoryLogCreateWithoutUserInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput | Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutUserInput | Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyUserInputEnvelope
  set?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  disconnect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  delete?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  update?: Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutUserInput | Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.VariantInventoryLogUpdateManyWithWhereWithoutUserInput | Prisma.VariantInventoryLogUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.VariantInventoryLogScalarWhereInput | Prisma.VariantInventoryLogScalarWhereInput[]
}

export type VariantInventoryLogUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutUserInput, Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput> | Prisma.VariantInventoryLogCreateWithoutUserInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput | Prisma.VariantInventoryLogCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutUserInput | Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyUserInputEnvelope
  set?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  disconnect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  delete?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  update?: Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutUserInput | Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.VariantInventoryLogUpdateManyWithWhereWithoutUserInput | Prisma.VariantInventoryLogUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.VariantInventoryLogScalarWhereInput | Prisma.VariantInventoryLogScalarWhereInput[]
}

export type VariantInventoryLogCreateNestedManyWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput> | Prisma.VariantInventoryLogCreateWithoutVariantInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput | Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyVariantInputEnvelope
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
}

export type VariantInventoryLogUncheckedCreateNestedManyWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput> | Prisma.VariantInventoryLogCreateWithoutVariantInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput | Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyVariantInputEnvelope
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
}

export type VariantInventoryLogUpdateManyWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput> | Prisma.VariantInventoryLogCreateWithoutVariantInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput | Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput[]
  upsert?: Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutVariantInput | Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutVariantInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyVariantInputEnvelope
  set?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  disconnect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  delete?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  update?: Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutVariantInput | Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutVariantInput[]
  updateMany?: Prisma.VariantInventoryLogUpdateManyWithWhereWithoutVariantInput | Prisma.VariantInventoryLogUpdateManyWithWhereWithoutVariantInput[]
  deleteMany?: Prisma.VariantInventoryLogScalarWhereInput | Prisma.VariantInventoryLogScalarWhereInput[]
}

export type VariantInventoryLogUncheckedUpdateManyWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput> | Prisma.VariantInventoryLogCreateWithoutVariantInput[] | Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput | Prisma.VariantInventoryLogCreateOrConnectWithoutVariantInput[]
  upsert?: Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutVariantInput | Prisma.VariantInventoryLogUpsertWithWhereUniqueWithoutVariantInput[]
  createMany?: Prisma.VariantInventoryLogCreateManyVariantInputEnvelope
  set?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  disconnect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  delete?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  connect?: Prisma.VariantInventoryLogWhereUniqueInput | Prisma.VariantInventoryLogWhereUniqueInput[]
  update?: Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutVariantInput | Prisma.VariantInventoryLogUpdateWithWhereUniqueWithoutVariantInput[]
  updateMany?: Prisma.VariantInventoryLogUpdateManyWithWhereWithoutVariantInput | Prisma.VariantInventoryLogUpdateManyWithWhereWithoutVariantInput[]
  deleteMany?: Prisma.VariantInventoryLogScalarWhereInput | Prisma.VariantInventoryLogScalarWhereInput[]
}

export type VariantInventoryLogCreateWithoutUserInput = {
  id?: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
  variant: Prisma.ProductVariantCreateNestedOneWithoutInventoryLogsInput
}

export type VariantInventoryLogUncheckedCreateWithoutUserInput = {
  id?: string
  variantId: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
}

export type VariantInventoryLogCreateOrConnectWithoutUserInput = {
  where: Prisma.VariantInventoryLogWhereUniqueInput
  create: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutUserInput, Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput>
}

export type VariantInventoryLogCreateManyUserInputEnvelope = {
  data: Prisma.VariantInventoryLogCreateManyUserInput | Prisma.VariantInventoryLogCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type VariantInventoryLogUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.VariantInventoryLogWhereUniqueInput
  update: Prisma.XOR<Prisma.VariantInventoryLogUpdateWithoutUserInput, Prisma.VariantInventoryLogUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutUserInput, Prisma.VariantInventoryLogUncheckedCreateWithoutUserInput>
}

export type VariantInventoryLogUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.VariantInventoryLogWhereUniqueInput
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateWithoutUserInput, Prisma.VariantInventoryLogUncheckedUpdateWithoutUserInput>
}

export type VariantInventoryLogUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.VariantInventoryLogScalarWhereInput
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateManyMutationInput, Prisma.VariantInventoryLogUncheckedUpdateManyWithoutUserInput>
}

export type VariantInventoryLogScalarWhereInput = {
  AND?: Prisma.VariantInventoryLogScalarWhereInput | Prisma.VariantInventoryLogScalarWhereInput[]
  OR?: Prisma.VariantInventoryLogScalarWhereInput[]
  NOT?: Prisma.VariantInventoryLogScalarWhereInput | Prisma.VariantInventoryLogScalarWhereInput[]
  id?: Prisma.StringFilter<"VariantInventoryLog"> | string
  variantId?: Prisma.StringFilter<"VariantInventoryLog"> | string
  userId?: Prisma.StringFilter<"VariantInventoryLog"> | string
  delta?: Prisma.IntFilter<"VariantInventoryLog"> | number
  reason?: Prisma.StringFilter<"VariantInventoryLog"> | string
  note?: Prisma.StringNullableFilter<"VariantInventoryLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VariantInventoryLog"> | Date | string
}

export type VariantInventoryLogCreateWithoutVariantInput = {
  id?: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVariantInventoryLogsInput
}

export type VariantInventoryLogUncheckedCreateWithoutVariantInput = {
  id?: string
  userId: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
}

export type VariantInventoryLogCreateOrConnectWithoutVariantInput = {
  where: Prisma.VariantInventoryLogWhereUniqueInput
  create: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput>
}

export type VariantInventoryLogCreateManyVariantInputEnvelope = {
  data: Prisma.VariantInventoryLogCreateManyVariantInput | Prisma.VariantInventoryLogCreateManyVariantInput[]
  skipDuplicates?: boolean
}

export type VariantInventoryLogUpsertWithWhereUniqueWithoutVariantInput = {
  where: Prisma.VariantInventoryLogWhereUniqueInput
  update: Prisma.XOR<Prisma.VariantInventoryLogUpdateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedUpdateWithoutVariantInput>
  create: Prisma.XOR<Prisma.VariantInventoryLogCreateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedCreateWithoutVariantInput>
}

export type VariantInventoryLogUpdateWithWhereUniqueWithoutVariantInput = {
  where: Prisma.VariantInventoryLogWhereUniqueInput
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateWithoutVariantInput, Prisma.VariantInventoryLogUncheckedUpdateWithoutVariantInput>
}

export type VariantInventoryLogUpdateManyWithWhereWithoutVariantInput = {
  where: Prisma.VariantInventoryLogScalarWhereInput
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateManyMutationInput, Prisma.VariantInventoryLogUncheckedUpdateManyWithoutVariantInput>
}

export type VariantInventoryLogCreateManyUserInput = {
  id?: string
  variantId: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
}

export type VariantInventoryLogUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.ProductVariantUpdateOneRequiredWithoutInventoryLogsNestedInput
}

export type VariantInventoryLogUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VariantInventoryLogUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VariantInventoryLogCreateManyVariantInput = {
  id?: string
  userId: string
  delta: number
  reason: string
  note?: string | null
  createdAt?: Date | string
}

export type VariantInventoryLogUpdateWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVariantInventoryLogsNestedInput
}

export type VariantInventoryLogUncheckedUpdateWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VariantInventoryLogUncheckedUpdateManyWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type VariantInventoryLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  variantId?: boolean
  userId?: boolean
  delta?: boolean
  reason?: boolean
  note?: boolean
  createdAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["variantInventoryLog"]>

export type VariantInventoryLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  variantId?: boolean
  userId?: boolean
  delta?: boolean
  reason?: boolean
  note?: boolean
  createdAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["variantInventoryLog"]>

export type VariantInventoryLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  variantId?: boolean
  userId?: boolean
  delta?: boolean
  reason?: boolean
  note?: boolean
  createdAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["variantInventoryLog"]>

export type VariantInventoryLogSelectScalar = {
  id?: boolean
  variantId?: boolean
  userId?: boolean
  delta?: boolean
  reason?: boolean
  note?: boolean
  createdAt?: boolean
}

export type VariantInventoryLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "variantId" | "userId" | "delta" | "reason" | "note" | "createdAt", ExtArgs["result"]["variantInventoryLog"]>
export type VariantInventoryLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type VariantInventoryLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type VariantInventoryLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $VariantInventoryLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VariantInventoryLog"
  objects: {
    variant: Prisma.$ProductVariantPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    variantId: string
    userId: string
    delta: number
    reason: string
    note: string | null
    createdAt: Date
  }, ExtArgs["result"]["variantInventoryLog"]>
  composites: {}
}

export type VariantInventoryLogGetPayload<S extends boolean | null | undefined | VariantInventoryLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload, S>

export type VariantInventoryLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VariantInventoryLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VariantInventoryLogCountAggregateInputType | true
  }

export interface VariantInventoryLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VariantInventoryLog'], meta: { name: 'VariantInventoryLog' } }
  /**
   * Find zero or one VariantInventoryLog that matches the filter.
   * @param {VariantInventoryLogFindUniqueArgs} args - Arguments to find a VariantInventoryLog
   * @example
   * // Get one VariantInventoryLog
   * const variantInventoryLog = await prisma.variantInventoryLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VariantInventoryLogFindUniqueArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VariantInventoryLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VariantInventoryLogFindUniqueOrThrowArgs} args - Arguments to find a VariantInventoryLog
   * @example
   * // Get one VariantInventoryLog
   * const variantInventoryLog = await prisma.variantInventoryLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VariantInventoryLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VariantInventoryLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogFindFirstArgs} args - Arguments to find a VariantInventoryLog
   * @example
   * // Get one VariantInventoryLog
   * const variantInventoryLog = await prisma.variantInventoryLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VariantInventoryLogFindFirstArgs>(args?: Prisma.SelectSubset<T, VariantInventoryLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VariantInventoryLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogFindFirstOrThrowArgs} args - Arguments to find a VariantInventoryLog
   * @example
   * // Get one VariantInventoryLog
   * const variantInventoryLog = await prisma.variantInventoryLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VariantInventoryLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VariantInventoryLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VariantInventoryLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VariantInventoryLogs
   * const variantInventoryLogs = await prisma.variantInventoryLog.findMany()
   * 
   * // Get first 10 VariantInventoryLogs
   * const variantInventoryLogs = await prisma.variantInventoryLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const variantInventoryLogWithIdOnly = await prisma.variantInventoryLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VariantInventoryLogFindManyArgs>(args?: Prisma.SelectSubset<T, VariantInventoryLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VariantInventoryLog.
   * @param {VariantInventoryLogCreateArgs} args - Arguments to create a VariantInventoryLog.
   * @example
   * // Create one VariantInventoryLog
   * const VariantInventoryLog = await prisma.variantInventoryLog.create({
   *   data: {
   *     // ... data to create a VariantInventoryLog
   *   }
   * })
   * 
   */
  create<T extends VariantInventoryLogCreateArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogCreateArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VariantInventoryLogs.
   * @param {VariantInventoryLogCreateManyArgs} args - Arguments to create many VariantInventoryLogs.
   * @example
   * // Create many VariantInventoryLogs
   * const variantInventoryLog = await prisma.variantInventoryLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VariantInventoryLogCreateManyArgs>(args?: Prisma.SelectSubset<T, VariantInventoryLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VariantInventoryLogs and returns the data saved in the database.
   * @param {VariantInventoryLogCreateManyAndReturnArgs} args - Arguments to create many VariantInventoryLogs.
   * @example
   * // Create many VariantInventoryLogs
   * const variantInventoryLog = await prisma.variantInventoryLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VariantInventoryLogs and only return the `id`
   * const variantInventoryLogWithIdOnly = await prisma.variantInventoryLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VariantInventoryLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VariantInventoryLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VariantInventoryLog.
   * @param {VariantInventoryLogDeleteArgs} args - Arguments to delete one VariantInventoryLog.
   * @example
   * // Delete one VariantInventoryLog
   * const VariantInventoryLog = await prisma.variantInventoryLog.delete({
   *   where: {
   *     // ... filter to delete one VariantInventoryLog
   *   }
   * })
   * 
   */
  delete<T extends VariantInventoryLogDeleteArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogDeleteArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VariantInventoryLog.
   * @param {VariantInventoryLogUpdateArgs} args - Arguments to update one VariantInventoryLog.
   * @example
   * // Update one VariantInventoryLog
   * const variantInventoryLog = await prisma.variantInventoryLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VariantInventoryLogUpdateArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogUpdateArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VariantInventoryLogs.
   * @param {VariantInventoryLogDeleteManyArgs} args - Arguments to filter VariantInventoryLogs to delete.
   * @example
   * // Delete a few VariantInventoryLogs
   * const { count } = await prisma.variantInventoryLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VariantInventoryLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, VariantInventoryLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VariantInventoryLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VariantInventoryLogs
   * const variantInventoryLog = await prisma.variantInventoryLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VariantInventoryLogUpdateManyArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VariantInventoryLogs and returns the data updated in the database.
   * @param {VariantInventoryLogUpdateManyAndReturnArgs} args - Arguments to update many VariantInventoryLogs.
   * @example
   * // Update many VariantInventoryLogs
   * const variantInventoryLog = await prisma.variantInventoryLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VariantInventoryLogs and only return the `id`
   * const variantInventoryLogWithIdOnly = await prisma.variantInventoryLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VariantInventoryLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VariantInventoryLog.
   * @param {VariantInventoryLogUpsertArgs} args - Arguments to update or create a VariantInventoryLog.
   * @example
   * // Update or create a VariantInventoryLog
   * const variantInventoryLog = await prisma.variantInventoryLog.upsert({
   *   create: {
   *     // ... data to create a VariantInventoryLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VariantInventoryLog we want to update
   *   }
   * })
   */
  upsert<T extends VariantInventoryLogUpsertArgs>(args: Prisma.SelectSubset<T, VariantInventoryLogUpsertArgs<ExtArgs>>): Prisma.Prisma__VariantInventoryLogClient<runtime.Types.Result.GetResult<Prisma.$VariantInventoryLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VariantInventoryLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogCountArgs} args - Arguments to filter VariantInventoryLogs to count.
   * @example
   * // Count the number of VariantInventoryLogs
   * const count = await prisma.variantInventoryLog.count({
   *   where: {
   *     // ... the filter for the VariantInventoryLogs we want to count
   *   }
   * })
  **/
  count<T extends VariantInventoryLogCountArgs>(
    args?: Prisma.Subset<T, VariantInventoryLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VariantInventoryLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VariantInventoryLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VariantInventoryLogAggregateArgs>(args: Prisma.Subset<T, VariantInventoryLogAggregateArgs>): Prisma.PrismaPromise<GetVariantInventoryLogAggregateType<T>>

  /**
   * Group by VariantInventoryLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VariantInventoryLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VariantInventoryLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VariantInventoryLogGroupByArgs['orderBy'] }
      : { orderBy?: VariantInventoryLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VariantInventoryLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVariantInventoryLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VariantInventoryLog model
 */
readonly fields: VariantInventoryLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VariantInventoryLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VariantInventoryLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  variant<T extends Prisma.ProductVariantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductVariantDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductVariantClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VariantInventoryLog model
 */
export interface VariantInventoryLogFieldRefs {
  readonly id: Prisma.FieldRef<"VariantInventoryLog", 'String'>
  readonly variantId: Prisma.FieldRef<"VariantInventoryLog", 'String'>
  readonly userId: Prisma.FieldRef<"VariantInventoryLog", 'String'>
  readonly delta: Prisma.FieldRef<"VariantInventoryLog", 'Int'>
  readonly reason: Prisma.FieldRef<"VariantInventoryLog", 'String'>
  readonly note: Prisma.FieldRef<"VariantInventoryLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"VariantInventoryLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VariantInventoryLog findUnique
 */
export type VariantInventoryLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * Filter, which VariantInventoryLog to fetch.
   */
  where: Prisma.VariantInventoryLogWhereUniqueInput
}

/**
 * VariantInventoryLog findUniqueOrThrow
 */
export type VariantInventoryLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * Filter, which VariantInventoryLog to fetch.
   */
  where: Prisma.VariantInventoryLogWhereUniqueInput
}

/**
 * VariantInventoryLog findFirst
 */
export type VariantInventoryLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * Filter, which VariantInventoryLog to fetch.
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VariantInventoryLogs to fetch.
   */
  orderBy?: Prisma.VariantInventoryLogOrderByWithRelationInput | Prisma.VariantInventoryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VariantInventoryLogs.
   */
  cursor?: Prisma.VariantInventoryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VariantInventoryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VariantInventoryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VariantInventoryLogs.
   */
  distinct?: Prisma.VariantInventoryLogScalarFieldEnum | Prisma.VariantInventoryLogScalarFieldEnum[]
}

/**
 * VariantInventoryLog findFirstOrThrow
 */
export type VariantInventoryLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * Filter, which VariantInventoryLog to fetch.
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VariantInventoryLogs to fetch.
   */
  orderBy?: Prisma.VariantInventoryLogOrderByWithRelationInput | Prisma.VariantInventoryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VariantInventoryLogs.
   */
  cursor?: Prisma.VariantInventoryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VariantInventoryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VariantInventoryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VariantInventoryLogs.
   */
  distinct?: Prisma.VariantInventoryLogScalarFieldEnum | Prisma.VariantInventoryLogScalarFieldEnum[]
}

/**
 * VariantInventoryLog findMany
 */
export type VariantInventoryLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * Filter, which VariantInventoryLogs to fetch.
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VariantInventoryLogs to fetch.
   */
  orderBy?: Prisma.VariantInventoryLogOrderByWithRelationInput | Prisma.VariantInventoryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VariantInventoryLogs.
   */
  cursor?: Prisma.VariantInventoryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VariantInventoryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VariantInventoryLogs.
   */
  skip?: number
  distinct?: Prisma.VariantInventoryLogScalarFieldEnum | Prisma.VariantInventoryLogScalarFieldEnum[]
}

/**
 * VariantInventoryLog create
 */
export type VariantInventoryLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * The data needed to create a VariantInventoryLog.
   */
  data: Prisma.XOR<Prisma.VariantInventoryLogCreateInput, Prisma.VariantInventoryLogUncheckedCreateInput>
}

/**
 * VariantInventoryLog createMany
 */
export type VariantInventoryLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VariantInventoryLogs.
   */
  data: Prisma.VariantInventoryLogCreateManyInput | Prisma.VariantInventoryLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VariantInventoryLog createManyAndReturn
 */
export type VariantInventoryLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * The data used to create many VariantInventoryLogs.
   */
  data: Prisma.VariantInventoryLogCreateManyInput | Prisma.VariantInventoryLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VariantInventoryLog update
 */
export type VariantInventoryLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * The data needed to update a VariantInventoryLog.
   */
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateInput, Prisma.VariantInventoryLogUncheckedUpdateInput>
  /**
   * Choose, which VariantInventoryLog to update.
   */
  where: Prisma.VariantInventoryLogWhereUniqueInput
}

/**
 * VariantInventoryLog updateMany
 */
export type VariantInventoryLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VariantInventoryLogs.
   */
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateManyMutationInput, Prisma.VariantInventoryLogUncheckedUpdateManyInput>
  /**
   * Filter which VariantInventoryLogs to update
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * Limit how many VariantInventoryLogs to update.
   */
  limit?: number
}

/**
 * VariantInventoryLog updateManyAndReturn
 */
export type VariantInventoryLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * The data used to update VariantInventoryLogs.
   */
  data: Prisma.XOR<Prisma.VariantInventoryLogUpdateManyMutationInput, Prisma.VariantInventoryLogUncheckedUpdateManyInput>
  /**
   * Filter which VariantInventoryLogs to update
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * Limit how many VariantInventoryLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VariantInventoryLog upsert
 */
export type VariantInventoryLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * The filter to search for the VariantInventoryLog to update in case it exists.
   */
  where: Prisma.VariantInventoryLogWhereUniqueInput
  /**
   * In case the VariantInventoryLog found by the `where` argument doesn't exist, create a new VariantInventoryLog with this data.
   */
  create: Prisma.XOR<Prisma.VariantInventoryLogCreateInput, Prisma.VariantInventoryLogUncheckedCreateInput>
  /**
   * In case the VariantInventoryLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VariantInventoryLogUpdateInput, Prisma.VariantInventoryLogUncheckedUpdateInput>
}

/**
 * VariantInventoryLog delete
 */
export type VariantInventoryLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
  /**
   * Filter which VariantInventoryLog to delete.
   */
  where: Prisma.VariantInventoryLogWhereUniqueInput
}

/**
 * VariantInventoryLog deleteMany
 */
export type VariantInventoryLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VariantInventoryLogs to delete
   */
  where?: Prisma.VariantInventoryLogWhereInput
  /**
   * Limit how many VariantInventoryLogs to delete.
   */
  limit?: number
}

/**
 * VariantInventoryLog without action
 */
export type VariantInventoryLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VariantInventoryLog
   */
  select?: Prisma.VariantInventoryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VariantInventoryLog
   */
  omit?: Prisma.VariantInventoryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInventoryLogInclude<ExtArgs> | null
}
